# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voc_pb2 as voc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InterpreterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseQuestion = channel.unary_unary(
                '/a2a.Interpreter/ParseQuestion',
                request_serializer=voc__pb2.ParseQuestionReq.SerializeToString,
                response_deserializer=voc__pb2.ParseQuestionRes.FromString,
                _registered_method=True)


class InterpreterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterpreterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseQuestion,
                    request_deserializer=voc__pb2.ParseQuestionReq.FromString,
                    response_serializer=voc__pb2.ParseQuestionRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Interpreter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Interpreter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Interpreter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Interpreter/ParseQuestion',
            voc__pb2.ParseQuestionReq.SerializeToString,
            voc__pb2.ParseQuestionRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RetrieverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/a2a.Retriever/Retrieve',
                request_serializer=voc__pb2.RetrieveReq.SerializeToString,
                response_deserializer=voc__pb2.RetrieveRes.FromString,
                _registered_method=True)


class RetrieverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrieverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=voc__pb2.RetrieveReq.FromString,
                    response_serializer=voc__pb2.RetrieveRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Retriever', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Retriever', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Retriever(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Retriever/Retrieve',
            voc__pb2.RetrieveReq.SerializeToString,
            voc__pb2.RetrieveRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SummarizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeCandidates = channel.unary_unary(
                '/a2a.Summarizer/MakeCandidates',
                request_serializer=voc__pb2.SummarizeReq.SerializeToString,
                response_deserializer=voc__pb2.SummarizeRes.FromString,
                _registered_method=True)
        self.Refine = channel.unary_unary(
                '/a2a.Summarizer/Refine',
                request_serializer=voc__pb2.RefineReq.SerializeToString,
                response_deserializer=voc__pb2.RefineRes.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/a2a.Summarizer/RunPipeline',
                request_serializer=voc__pb2.RunPipelineReq.SerializeToString,
                response_deserializer=voc__pb2.RunPipelineRes.FromString,
                _registered_method=True)


class SummarizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCandidates,
                    request_deserializer=voc__pb2.SummarizeReq.FromString,
                    response_serializer=voc__pb2.SummarizeRes.SerializeToString,
            ),
            'Refine': grpc.unary_unary_rpc_method_handler(
                    servicer.Refine,
                    request_deserializer=voc__pb2.RefineReq.FromString,
                    response_serializer=voc__pb2.RefineRes.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=voc__pb2.RunPipelineReq.FromString,
                    response_serializer=voc__pb2.RunPipelineRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Summarizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Summarizer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Summarizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Summarizer/MakeCandidates',
            voc__pb2.SummarizeReq.SerializeToString,
            voc__pb2.SummarizeRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Summarizer/Refine',
            voc__pb2.RefineReq.SerializeToString,
            voc__pb2.RefineRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Summarizer/RunPipeline',
            voc__pb2.RunPipelineReq.SerializeToString,
            voc__pb2.RunPipelineRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EvaluatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/a2a.Evaluator/Evaluate',
                request_serializer=voc__pb2.EvaluateReq.SerializeToString,
                response_deserializer=voc__pb2.EvaluateRes.FromString,
                _registered_method=True)


class EvaluatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=voc__pb2.EvaluateReq.FromString,
                    response_serializer=voc__pb2.EvaluateRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Evaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Evaluator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Evaluator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Evaluator/Evaluate',
            voc__pb2.EvaluateReq.SerializeToString,
            voc__pb2.EvaluateRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CriticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Review = channel.unary_unary(
                '/a2a.Critic/Review',
                request_serializer=voc__pb2.ReviewReq.SerializeToString,
                response_deserializer=voc__pb2.ReviewRes.FromString,
                _registered_method=True)


class CriticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Review(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CriticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=voc__pb2.ReviewReq.FromString,
                    response_serializer=voc__pb2.ReviewRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Critic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Critic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Critic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Critic/Review',
            voc__pb2.ReviewReq.SerializeToString,
            voc__pb2.ReviewRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImproverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Improve = channel.unary_unary(
                '/a2a.Improver/Improve',
                request_serializer=voc__pb2.PolicyReq.SerializeToString,
                response_deserializer=voc__pb2.PolicyRes.FromString,
                _registered_method=True)
        self.Refine = channel.unary_unary(
                '/a2a.Improver/Refine',
                request_serializer=voc__pb2.RefinePolicyReq.SerializeToString,
                response_deserializer=voc__pb2.PolicyRes.FromString,
                _registered_method=True)
        self.RunPolicyPipeline = channel.unary_unary(
                '/a2a.Improver/RunPolicyPipeline',
                request_serializer=voc__pb2.RunPolicyPipelineReq.SerializeToString,
                response_deserializer=voc__pb2.RunPolicyPipelineRes.FromString,
                _registered_method=True)


class ImproverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Improve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPolicyPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImproverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Improve': grpc.unary_unary_rpc_method_handler(
                    servicer.Improve,
                    request_deserializer=voc__pb2.PolicyReq.FromString,
                    response_serializer=voc__pb2.PolicyRes.SerializeToString,
            ),
            'Refine': grpc.unary_unary_rpc_method_handler(
                    servicer.Refine,
                    request_deserializer=voc__pb2.RefinePolicyReq.FromString,
                    response_serializer=voc__pb2.PolicyRes.SerializeToString,
            ),
            'RunPolicyPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPolicyPipeline,
                    request_deserializer=voc__pb2.RunPolicyPipelineReq.FromString,
                    response_serializer=voc__pb2.RunPolicyPipelineRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.Improver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.Improver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Improver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Improve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Improver/Improve',
            voc__pb2.PolicyReq.SerializeToString,
            voc__pb2.PolicyRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Improver/Refine',
            voc__pb2.RefinePolicyReq.SerializeToString,
            voc__pb2.PolicyRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPolicyPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.Improver/RunPolicyPipeline',
            voc__pb2.RunPolicyPipelineReq.SerializeToString,
            voc__pb2.RunPolicyPipelineRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
