[pytest]
addopts = -v --cov=app --cov=quality --cov-report=term-missing --cov-report=html:tests_output/htmlcov --cov-report=xml:tests_output/coverage.xml --junitxml=tests_output/junit.xml
testpaths = tests
